# TEMPLATE FROM CHATGPT
# name: Run Selenium Bot Daily

# on:
#   schedule:
#     - cron: "0 6 * * *"  # Run daily at 6:00 AM UTC

# jobs:
#   run-docker-bot:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Build Docker Image
#         run: docker build -t selenium-bot .

#       - name: Run Selenium Bot
#           env:
#             USERNAME: ${{ secrets.USERNAME }}
#             PASSWORD: ${{ secrets.PASSWORD }}
#         run: docker run selenium-bot
