name: Run Selenium Bot Daily

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at 00:00 AM UTC
  workflow_dispatch:

jobs:
  run-docker-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium Bot
        env:
          SPAT_URL: ${{ secrets.SPAT_URL }}
          SPAT_USERNAME: ${{ secrets.SPAT_USERNAME }}
          SPAT_PASSWORD: ${{ secrets.SPAT_PASSWORD }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: python main.py

      - name: Echo Bot Finished
        run: echo "Bot finished running"
