name: Run Selenium Bot Daily

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at 00:00 AM UTC
  workflow_dispatch:

jobs:
  run-selenium-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium Bot
        env:
          SPAT_URL: ${{ secrets.SPAT_URL }}
          SPAT_USERNAME: ${{ secrets.SPAT_USERNAME }}
          SPAT_PASSWORD: ${{ secrets.SPAT_PASSWORD }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: python main.py

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "*.png"

      - name: Echo Bot Finished
        run: echo "Bot finished running"
